trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: Create resource group
  inputs:
    azureSubscription: 'create-resource-group-service-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 
      az deployment sub create -l eastus -f create-rg.bicep --parameters rgName=web-app-$(Build.BuildId)-rg
      
- task: AzureCLI@2
  displayName: Create web app in resource group
  inputs:
    azureSubscription: 'create-resource-group-service-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 
      az deployment group create -g web-app-$(Build.BuildId)-rg -f webAppDeploymentDemo.bicep --parameters webAppName=web-app-for-cam-rg-$(Build.BuildId)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'github-deployment-artifact'
    publishLocation: 'Container'